### ISSUE TITLE
The curse page says not to use this addon on clasic retail servers. 

### ISSUE THREAD

**Issue by ideceddy** [DeadlyBossMods/DBM-BCVanilla#21]
**Describe the bug**
The curse page says that we should not install this addon on classic retail servers.

**Do you have an error log of what happened?**
Please check https://www.curseforge.com/wow/addons/dbm-bc

**To Reproduce**
Go to https://www.curseforge.com/wow/addons/dbm-bc

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by Molkree** [comment]
Yeah, so what is the issue here? For Classic you should use main DBM addon, classic version (look for `-classic` suffix).
Similar for Burning Crusade Classic, it has `-bcc` suffix.
https://www.curseforge.com/wow/addons/deadly-boss-mods/files
![image](https://user-images.githubusercontent.com/12860284/120577585-34013980-c42d-11eb-8467-8d3b22a0240c.png)
